test new cwd paths

diff --git a/.github/workflows/spdm-validator.yml b/.github/workflows/spdm-validator.yml
--- a/.github/workflows/spdm-validator.yml
+++ b/.github/workflows/spdm-validator.yml
@@ -74,81 +74,81 @@ jobs:
             core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
             core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
 
-      # - name: Checkout spdm-emu repository
-      #   uses: actions/checkout@v4
-      #   with:
-      #     repository: parvathib/spdm-emu
-      #     ref: pbhogaraju/custom-3.8.0
-      #     path: spdm-emu
-      #     submodules: recursive
+      - name: Checkout spdm-emu repository
+        uses: actions/checkout@v4
+        with:
+          repository: parvathib/spdm-emu
+          ref: pbhogaraju/custom-3.8.0
+          path: spdm-emu
+          submodules: recursive
 
-      # - name: Build spdm-emu
-      #   run: |
-      #     pushd spdm-emu
-      #     git submodule update --init --recursive
-      #     mkdir build
-      #     pushd build
-      #     cmake -DARCH=x64 -DTOOLCHAIN=GCC -DTARGET=Debug -DCRYPTO=openssl ..
-      #     make copy_sample_key
-      #     make
-      #     popd
-      #     popd
+      - name: Build spdm-emu
+        run: |
+          pushd spdm-emu
+          git submodule update --init --recursive
+          mkdir build
+          pushd build
+          cmake -DARCH=x64 -DTOOLCHAIN=GCC -DTARGET=Debug -DCRYPTO=openssl ..
+          make copy_sample_key
+          make
+          popd
+          popd
 
-      # - name: Run SPDM validator tests on MCTP transport
-      #   run: |
-      #     export SPDM_VALIDATOR_DIR=$GITHUB_WORKSPACE/spdm-emu/build/bin
-      #     cargo xtask all-build
-      #     cargo t -p tests-integration -- --test test_mctp_spdm_responder_conformance --nocapture  --include-ignored
-      #     sccache --show-stats
+      - name: Run SPDM validator tests on MCTP transport
+        run: |
+          export SPDM_VALIDATOR_DIR=$GITHUB_WORKSPACE/spdm-emu/build/bin
+          cargo xtask all-build
+          cargo t -p tests-integration -- --test test_mctp_spdm_responder_conformance --nocapture  --include-ignored
+          sccache --show-stats
 
-      # - name: Upload logs and traces for MCTP transport
-      #   if: always()
-      #   uses: actions/upload-artifact@v4
-      #   with:
-      #     name: spdm-mctp-validator-test-results
-      #     path: |
-      #       test.log
-      #       caliptra_spdm_validator.pcap
-      #       spdm-emu/build/bin/spdm_device_validator_output.txt
+      - name: Upload logs and traces for MCTP transport
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: spdm-mctp-validator-test-results
+          path: |
+            ${{ env.SPDM_VALIDATOR_DIR }}/test.log
+            ${{ env.SPDM_VALIDATOR_DIR }}/caliptra_spdm_validator.pcap
+            ${{ env.SPDM_VALIDATOR_DIR }}/spdm_device_validator_output.txt
 
-      # - name: Display SPDM Validator test results on MCTP transport
-      #   run: |
-      #     cat $GITHUB_WORKSPACE/test.log
+      - name: Display SPDM Validator test results on MCTP transport
+        run: |
+          cat $SPDM_VALIDATOR_DIR/test.log
 
-      # - name: Check for test failures on MCTP transport
-      #   run: |
-      #     if grep -E 'test suite \(.*\) - pass: [0-9]+, fail: [1-9][0-9]*' $GITHUB_WORKSPACE/test.log; then
-      #       echo "Test suite had failures."
-      #       exit 1
-      #     fi
+      - name: Check for test failures on MCTP transport
+        run: |
+          if grep -E 'test suite \(.*\) - pass: [0-9]+, fail: [1-9][0-9]*' $SPDM_VALIDATOR_DIR/test.log; then
+            echo "Test suite had failures."
+            exit 1
+          fi
 
-      # - name: Run SPDM validator tests on DOE transport
-      #   run: |
-      #     export SPDM_VALIDATOR_DIR=$GITHUB_WORKSPACE/spdm-emu/build/bin
-      #     cargo xtask all-build
-      #     cargo t -p tests-integration -- --test test_doe_spdm_responder_conformance --nocapture  --include-ignored
-      #     sccache --show-stats
+      - name: Run SPDM validator tests on DOE transport
+        run: |
+          export SPDM_VALIDATOR_DIR=$GITHUB_WORKSPACE/spdm-emu/build/bin
+          cargo xtask all-build
+          cargo t -p tests-integration -- --test test_doe_spdm_responder_conformance --nocapture  --include-ignored
+          sccache --show-stats
 
-      # - name: Upload logs and traces for DOE transport
-      #   if: always()
-      #   uses: actions/upload-artifact@v4
-      #   with:
-      #     name: spdm-doe-validator-test-results
-      #     path: |
-      #       test.log
-      #       caliptra_spdm_validator.pcap
-      #       spdm-emu/build/bin/spdm_device_validator_output.txt
+      - name: Upload logs and traces for DOE transport
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: spdm-doe-validator-test-results
+          path: |
+            ${{ env.SPDM_VALIDATOR_DIR }}/test.log
+            ${{ env.SPDM_VALIDATOR_DIR }}/caliptra_spdm_validator.pcap
+            ${{ env.SPDM_VALIDATOR_DIR }}/spdm_device_validator_output.txt
 
-      # - name: Display SPDM Validator test results for DOE transport
-      #   run: |
-      #     cat $GITHUB_WORKSPACE/test.log
+      - name: Display SPDM Validator test results for DOE transport
+        run: |
+          cat $SPDM_VALIDATOR_DIR/test.log
 
-      # - name: Check for test failures on DOE transport
-      #   run: |
-      #     if grep -E 'test suite \(.*\) - pass: [0-9]+, fail: [1-9][0-9]*' $GITHUB_WORKSPACE/test.log; then
-      #       echo "Test suite had failures."
-      #       exit 1
-      #     fi
+      - name: Check for test failures on DOE transport
+        run: |
+          if grep -E 'test suite \(.*\) - pass: [0-9]+, fail: [1-9][0-9]*' $SPDM_VALIDATOR_DIR/test.log; then
+            echo "Test suite had failures."
+            exit 1
+          fi
 
       - name: Checkout CCC spdm-rs repository
         uses: actions/checkout@v4
@@ -164,11 +164,7 @@ jobs:
           git submodule update --init --recursive
           sh_script/pre-build.sh
           cargo build
-          echo "Check if the target binary is available"
-          ls -l target/debug
-          echo "Copy test keys to target/debug"
           cp -r test_key target/debug/
-          echo "Check test keys"
           ls -l target/debug/test_key/ecp384/
 
       - name: Run CCC spdm-requester-emu tests for TDISP+IDE
@@ -180,7 +176,7 @@ jobs:
 
       - name: Display CCC spdm-requester-emu test results for TDISP+IDE
         run: |
-          cat $GITHUB_WORKSPACE/spdm-rs/target/debug/tdisp_ide_validator_output.txt
+          cat $SPDM_VALIDATOR_DIR/tdisp_ide_validator_output.txt
 
       - name: Upload CCC spdm-requester-emu test results for TDISP+IDE
         if: always()
@@ -188,4 +184,4 @@ jobs:
         with:
           name: spdm-tdisp-ide-validator-test-results
           path: |
-            spdm-rs/target/debug/tdisp_ide_validator_output.txt
+            ${{ env.SPDM_VALIDATOR_DIR }}/tdisp_ide_validator_output.txt
